import os

USER_BROWSER_SESSION_PATH = os.getenv('USER_BROWSER_SESSION_PATH')
HEADLESS = bool(os.getenv('HEADLESS'))
TELEGRAM_TOKEN = os.getenv('TELEGRAM_TOKEN')
TELEGRAM_CHAT_ID = os.getenv('TELEGRAM_CHAT_ID')
